#!/usr/bin/bash

# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# do set -x for development/debugging
set -eu

# we cannot override %__scm_setup_patch b/c it is called from %autosetup
# and some specs have %setup + %autopatch, so we need to make sure
# the git repo exists here
if [ ! -d .git ]; then
  git init
  git add .
  # that PWD magic prints the name of the PWD, which usually is NAME-VERSION
  git commit --allow-empty -a -m "${PWD##*/} base"
fi

if [ "$1" == "%{1}" ]; then
  # rpm pipes the patch here
  # also, Michal Domonkos is a genius
  patch_path=$(readlink -f /dev/stdin)
else
  patch_path=$1
fi
patch_name=$(basename $patch_path)
patch_id=$2

# we process first and second arg above, the rest is for patch
cat - | /usr/bin/patch ${@:3}

commit_message=$(cat << EOF
Apply patch ${patch_name}

patch_name: ${patch_name}
present_in_specfile: true
EOF
)
if [ "$patch_id" != "%{2}" ]; then
  # concat 2 strings and separate them with \n - a nightmare to do in bash
  printf -v commit_message "${commit_message}\nlocation_in_specfile: ${patch_id}"
fi

git add .
# patches can be empty, rpmbuild if fine with it
git commit -m "$commit_message" --allow-empty
